name: Terraform Deploy

on:
  workflow_call:
    secrets:
      aws_access_key_id:
        required: true
        description: 'AWS Access Key ID'
      aws_secret_access_key:
        required: true
        description: 'AWS Secret Access Key'
      aws_session_token:
        required: true
        description: 'AWS Session Token (optional for temporary credentials)'
      docker_hub_user:
        required: true
        description: 'Docker Hub username for image tagging'
    inputs:
      aws_region:
        required: true
        type: string
        description: 'AWS Region for deployment'
      tf_main_bucket_name:
        required: true
        type: string
        description: 'S3 bucket name for Terraform backend'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Short Commit Hash
        run: echo "TC_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-session-token: ${{ secrets.aws_session_token }}
          aws-region: ${{ inputs.aws_region }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./devops/terraform
        run: |
          export TF_LOG=DEBUG
          terraform init \
            -backend-config="bucket=${{ inputs.tf_main_bucket_name }}" \
            -backend-config="key=processor-service/terraform.tfstate" \
            -backend-config="region=${{ inputs.aws_region }}" \
            -backend-config="encrypt=true"

      - name: Terraform Apply
        working-directory: ./devops/terraform
        run: |
          terraform apply -auto-approve \
            -var "tc_image_tag=${{ env.TC_IMAGE_TAG }}" \
            -var "aws_access_key_id=${{ secrets.aws_access_key_id }}" \
            -var "aws_secret_access_key=${{ secrets.aws_secret_access_key }}" \
            -var "aws_session_token=${{ secrets.aws_session_token }}" \
            -var "aws_bucket_name=${{ inputs.tf_main_bucket_name }}" \
            -var "aws_region=${{ inputs.aws_region }}" \
            -var "docker_hub_user=${{ secrets.docker_hub_user }}"